import type { ProductProfile } from './products.js';
import type { NewStop } from './types.js';
const checkedOn = '2026-09-19';
const profile = (categories: ProductProfile['categories'], evidence: string, source: string, photos: ProductProfile['photos'], opacity: ProductProfile['opacity']='opaque'): ProductProfile => ({categories,business:'manufacturer',opacity,evidence,source,photos,checkedOn});
const photo = (url:string,caption:string,source:string) => ({url,caption,source});
/** Public catalogue evidence, not a factory audit or a LIMEX trial approval. */
export const VERIFIED_PRODUCTS: Record<string, ProductProfile> = {
  'K1-proton-polymer': profile(['hm-bags','plastic-bags','nonwoven-bags'], 'The company describes three manufacturing divisions and its own production of plastic bags. Its catalogue lists HM/HDPE pick-up bags, coloured medical-waste bags and non-woven shopping bags. Target opaque variants only.', 'https://www.protonpolymer.com/', [
    photo('https://cpimg.tistatic.com/02981335/b/5/HM-Hdpe-Pick-Up-Bags.jpg','HM / HDPE pick-up bags','https://www.tradeindia.com/products/hm-hdpe-pick-up-bags-c2981335.html'),
    photo('https://cpimg.tistatic.com/02981334/b/5/Non-Woven-Bags.jpg','Coloured non-woven bags','https://www.protonpolymer.com/non-woven-bags-2981334.html')]),
  'A10-balahanuman-plastic-industrial-pvt-ltd': profile(['plastic-bags'], 'Manufacturer listing describes in-house production and a black LDPE garbage bag. This match covers the black bags; transparent film and liner products are outside the target.', 'https://www.tradeindia.com/products/black-plastic-garbage-bag-c8452623.html', [photo('https://cpimg.tistatic.com/08452623/b/4/Black-Plastic-Garbage-Bag.jpg','Black LDPE garbage bags','https://www.tradeindia.com/products/black-plastic-garbage-bag-c8452623.html')]),
  'N3-euphoria-packaging': profile(['plastic-bags'], 'Company profile describes its bag-manufacturing machinery and co-extruded polyethylene packaging. Its product catalogue lists white/black LDPE courier bags. Target the opaque courier-bag line.', 'https://www.euphoriapackaging.com/company-profile.html', [photo('https://5.imimg.com/data5/SELLER/Default/2024/1/378567938/JU/TR/DA/6509583/ldpe-security-courier-bags-500x500.jpg','Opaque LDPE security courier bags','https://www.euphoriapack.in/')]),
  'N3-moldking-packaging-pvt-ltd': profile(['thinwall','dairy'], 'Company describes its own injection-moulded food-packaging production. Catalogue shows opaque coloured ice-cream tubs; confirm the unlabelled substrate and selected wall thickness with the factory.', 'https://moldking.in/', [photo('https://moldking.in/wp-content/uploads/2026/06/125ml-1-scaled.png','125 ml ice-cream tub','https://moldking.in/')]),
  'T1-satguru-plasticpack-llp-satguru-iml': profile(['thinwall','dairy'], 'Company describes manufacturing IML containers at its Ahmedabad facility. Catalogue includes opaque white and coloured ice-cream containers. Match is for these products, subject to factory confirmation of the substrate.', 'https://satguruiml.com/', [photo('https://satguruiml.com/wp-content/uploads/2024/07/80ml-Oval-ICe-Cream-IML-Container_D-44-80-768x576.png','Opaque IML ice-cream tubs','https://satguruiml.com/')]),
};
export interface ResearchedCompany {key:string;fields:NewStop;profile:ProductProfile;region:string}
export const RESEARCHED_COMPANIES: ResearchedCompany[] = [
 {key:'pm-plastic-chandrala',region:'Chandrala, Gandhinagar',fields:{name:'P. M. Plastic Industries',addr:'Survey No. 1007, Ahmedabad–Himmatnagar Highway, Chandrala, Gandhinagar, Gujarat',makes:'White PP woven bags and sacks; target opaque variants only',fit:'good'},profile:profile(['woven-bags'],'Company listing identifies a manufacturer of PP woven bags. Product page offers white PP woven sacks alongside other variants; only the opaque white range is relevant. Confirm factory extrusion and weaving before a trial.','https://www.tradeindia.com/products/pp-woven-bag-c5916522.html',[photo('https://cpimg.tistatic.com/05916522/b/5/PP-Woven-Bag.jpg','White PP woven sacks','https://www.tradeindia.com/products/pp-woven-bag-c5916522.html')])},
 {key:'hifi-plastic-toys-kuha',region:'Kuha, Ahmedabad',fields:{name:'Hifi Plastic Toys Industry',addr:'Plot No. 14, Ganesha Industrial Park, Kuha, Gujarat 382433',tel:'8610678712',makes:'Opaque coloured plastic toys: doctor sets and elephant toys',fit:'good'},profile:profile(['toys'],'Company website identifies direct toy manufacturing at Kuha; its manufacturer listing publishes machine-made coloured plastic doctor sets and elephant toys. This is Hifi Plastic Toys Industry, not HIFI Industries LLP. Confirm the polymer and in-house process before sampling.','https://hifi-plastic-toys.grexa.site/',[photo('https://img1.exportersindia.com/product_images/bc-small/2026/1/13254081/kids-doctor-set-1768371372-8534550.jpeg','Coloured plastic doctor-set toys','https://www.exportersindia.com/hifi-plastic-toys-industry/'),photo('https://img1.exportersindia.com/product_images/bc-small/2026/1/13254081/ball-elephant-toys-1768372020-8534601.jpeg','Coloured elephant toy','https://www.exportersindia.com/hifi-plastic-toys-industry/')])},
 {key:'anjali-polyplast-khopoli',region:'Khopoli, Maharashtra — outside Gujarat',fields:{name:'Anjali Polyplast Pvt Ltd',addr:'Factory: Plot No. 6, Universal Industrial Estate, Sajgaon, off Khopoli–Pen Road, Khopoli, Maharashtra 410203',tel:'02225662434',makes:'Milky-white HDPE blow-moulded bottles and opaque 5-litre jars; office phone listed',fit:'good'},profile:profile(['bottles','jars'],'Company identifies its own HDPE/PP blow-moulding factory in Khopoli. Technical catalogue explicitly lists milky-white HDPE bottles; pharmaceutical gallery shows white bottles and a 5-litre handled jar. Transparent jars are excluded. Office phone, not a verified factory contact.','https://anjalipolyplast.in/',[photo('https://anjalipolyplast.in/images/pharma/2025/1000ml500ml250ml.jpg','Milky-white bottle family','https://anjalipolyplast.in/pharma_product.php'),photo('https://anjalipolyplast.in/images/pharma/2025/CYLINDRICAL5LTRJARWITHHANDLE.jpg','Opaque 5-litre handled jar','https://anjalipolyplast.in/pharma_product.php')],'milky-white')},
];
/** Exact normalized names only: never merge unrelated businesses with similar names. */
export const companyNameKey=(name:string)=>name.toLowerCase().replace(/[^a-z0-9]/g,'');
export function researchedProfile(name:string) {return RESEARCHED_COMPANIES.find(c=>companyNameKey(c.fields.name)===companyNameKey(name))?.profile ?? null;}
